### ISSUE TITLE
Support Waku?

### ISSUE THREAD

**Issue by dai-shi** [kuma-ui/kuma-ui#208]
[Waku](https://github.com/dai-shi/waku) is an ongoing project to develop a React Server Component based framework. It would be super nice if we can support Waku+Kuma UI.

At a glance, there seems to be an issue with vite plugin which can't be resolvable on the Waku end. Though, Waku's support for CSS is still work in progress, so there might be potential challenges somewhere.

Just dropping a note to see if there could be a collaboration.

**Comment by poteboy** [comment]
Hi @dai-shi ,

I'm extremely thrilled to receive this offer. The opportunity of bringing together Waku and Kuma UI is indeed exciting and I sincerely appreciate your interest!

Regarding the vite plugin issue, I'm certainly willing to explore potential solutions and assist in any way possible. I'm absolutely open to collaboration and exploring how we can make this integration happen!

Waku-waku 🙌🙌

**Comment by dai-shi** [comment]
Waku-waku! 🤩 

Here's what I tried:
```bash
yarn create waku
cd waku-example
yarn add @kuma-ui/core @kuma-ui/vite
echo 'import { defineConfig } from "vite"; import KumaUI from "@kuma-ui/vite"; export default defineConfig({ plugins: [KumaUI()] });' > vite.config.js
yarn dev
```

The error is `TypeError [Error]: import_react.default.createContext is not a function` which probably means, we try to use KumaUI plugin in RSC and failed. But, I'm not very confident how it happens. Waku uses Vite in a weird way as Vite doesn't know anything about RSC.

**Comment by kotarella1110** [comment]
@dai-shi 

I resolved the issue on the Kuma side. For more details, please refer to the following comment:

https://github.com/poteboy/kuma-ui/pull/211#discussion_r1261225948

Afterwards, we tested the dev server and discovered that the @kuma-ui/vite package does not inject the style tags. This is because Kuma injects the style tags at runtime specifically for the dev server.

https://github.com/poteboy/kuma-ui/blob/b001a00219142f93cdfd1e497d5ad1b2e3b6a78d/packages/vite/src/index.ts#L114

Therefore, we decided to investigate by switching to the usage of virtual modules to import CSS. However, while it works in [Kuma's Vite example](https://github.com/poteboy/kuma-ui/tree/b5aaea2a05765e349d7144c03364d3d2bf261ada/example/vite), it doesn't work in Waku.

https://github.com/poteboy/kuma-ui/pull/211/commits/fda76390e53a61de16af99c0a8a948ece5b75a03

The error message is as follows:

```
[vite] Error when evaluating SSR module /src/components/App.tsx: failed to import "virtual:kuma-ui/Users/kotarella1110/Develop/sandbox/waku-example/src/components/App.css"
|- TypeError: Cannot read properties of undefined (reading 'get')                                  
    at TransformContext.transform (file:///Users/kotarella1110/Develop/sandbox/waku-example/node_modules/vite/dist/node/chunks/dep-210e5610.js:38307:56)
    at Object.transform (file:///Users/kotarella1110/Develop/sandbox/waku-example/node_modules/vite/dist/node/chunks/dep-210e5610.js:44199:62)
    at async loadAndTransform (file:///Users/kotarella1110/Develop/sandbox/waku-example/node_modules/vite/dist/node/chunks/dep-210e5610.js:54834:29)
    at async instantiateModule (file:///Users/kotarella1110/Develop/sandbox/waku-example/node_modules/vite/dist/node/chunks/dep-210e5610.js:55759:10)
```

I believe that if virtual module support can be added on the Raku side, Kuma should work without any issues. Is it possible to add support for virtual modules?

**Comment by dai-shi** [comment]
https://github.com/dai-shi/waku/pull/103 may (or may not) help for virtual modules.
You can install codesandbox-ci build.

btw, would you be interested in adding CodeSandbox CI in this project? It would make it easy to try a PR.

**Comment by dai-shi** [comment]
It seems to be working with https://github.com/dai-shi/waku/pull/103 and #211.

<img width="745" alt="image" src="https://github.com/poteboy/kuma-ui/assets/490574/8f7b0522-9103-43ca-9468-af70d723430a">

**Comment by kotarella1110** [comment]
> btw, would you be interested in adding CodeSandbox CI in this project? It would make it easy to try a PR.

I just learned about CodeSandbox CI, a useful GitHub app. I'll give it a try!

> It seems to be working with https://github.com/dai-shi/waku/pull/103 and https://github.com/poteboy/kuma-ui/pull/211.

That's wonderful! Thank you for your efforts 💚
I'll also check the functionality tonight. I'm feeling "Waku Waku" about doing that work 🤩

**Comment by dai-shi** [comment]
Thanks for trying. Should the virtual module be imported on client bundle, or server bundle? It's tricky because Waku uses Vite twice (or more) for RSC and for dev server. I will try your reproduction.

**Comment by dai-shi** [comment]
So, the first problem is even if we have `"@kuma-ui/core"` in App.tsx and add `import "virtual:kuma-ui/components/App.css";`, it's a server component and the import statement doesn't go to the browser.

Even if I manually add the import statement in main.tsx, it causes an error: `[vite] Internal server error: Failed to resolve import "virtual:kuma-ui/...`

I think this is also the problem with CSS Modules: Use css in a server component, and add the css file on client files.

**Comment by dai-shi** [comment]
https://github.com/dai-shi/waku/pull/103 is merged and https://github.com/dai-shi/waku/pull/106 is opened.
It's for CSS Modules, but the hope is to support virtual modules too.
So far, it doesn't work... 😢

**Comment by kotarella1110** [comment]
Thanks. I wil investigate it 👍

**Comment by kotarella1110** [comment]
@dai-shi 
I tried with the example below, but the 404 error was not reproduced...
https://github.com/kotarella1110-sandbox/waku-kuma-ui-example
Can anyone tell me how to reproduce the 404 error?

**Comment by dai-shi** [comment]
There seems to be an issue in Waku's ssr middleware. Please try this:

```diff
diff --git a/package.json b/package.json
index e99e0e1..820d083 100644
--- a/package.json
+++ b/package.json
@@ -4,7 +4,7 @@
   "type": "module",
   "private": true,
   "scripts": {
-    "dev": "waku dev --with-ssr",
+    "dev": "waku dev",
     "build": "waku build",
     "start": "waku start --with-ssr"
   },
```

**Comment by dai-shi** [comment]
Waku has been improved quite a lot since then.
It might be worth trying it again.

**Comment by kotarella1110** [comment]
Thanks for the update!
I'll give Waku another shot!!!!

**Comment by kotarella1110** [comment]
@dai-shi 

I attempted to launch the waku project before confirming integration with Kuma UI by executing the following commands:

```sh
pnpm create waku
cd waku-project
pnpm dev
```

However, it seems that the following error occurred:

```sh
> waku-project@0.0.0 dev /Users/kotarella1110/Develop/sandbox/waku-project
> waku dev --with-ssr

file:///Users/kotarella1110/Develop/sandbox/waku-project/node_modules/.pnpm/@hono+node-server@1.3.3/node_modules/@hono/node-server/dist/index.mjs:123
Object.setPrototypeOf(Response2, GlobalResponse);
       ^

TypeError: Object prototype may only be an Object or null: undefined
    at Function.setPrototypeOf (<anonymous>)
    at file:///Users/kotarella1110/Develop/sandbox/waku-project/node_modules/.pnpm/@hono+node-server@1.3.3/node_modules/@hono/node-server/dist/index.mjs:123:8
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
 ELIFECYCLE  Command failed with exit code 1.
```

Do you know what might be causing this issue?

**Comment by dai-shi** [comment]
I've never seen it. What's your Node.js version?

**Comment by kotarella1110** [comment]
Oops, I apologize :pray:
I forgot to switch the Node version and was using v16.
After switching to v18, the dev server started without any issues.
Thanks!

**Comment by kotarella1110** [comment]
@dai-shi 

I have installed the latest Waku and Kuma UI: https://github.com/kuma-ui/waku-kuma-ui-example/pull/1
But it seems that when I launch the dev server, the following error occurs:

```
Error: [vite] Named export 'useState' not found. The requested module 'react' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'react';
const {useState} = pkg;
```

To resolve this error, I can remove the line in `node_modules/@kuma-ui/vite/dist/index.mjs` that imports the virtual CSS module. After removing the following lines:

```diff
-       return `import "${url}";
- ` + result.code;
+ return result.code;
```

The dev server should start without any problems.
Is there a good way to resolve this?

**Comment by dai-shi** [comment]
Is the line importing `'react'`?

https://github.com/dai-shi/waku/pull/215 this might help.
Can you try this codesandbox build?
https://ci.codesandbox.io/status/dai-shi/waku/pr/215/builds/451677
Otherwise, I'm not sure...

**Comment by dai-shi** [comment]
There have been multiple improvements in the Waku side.
Can anyone try the latest version?

**Comment by dai-shi** [comment]
May I close this?
